#!/bin/sh
# If present, remove the editor/IDE one-line tool footer (see .cursor/rules/git-commits.mdc).
f=$1
[ -f "$f" ] || exit 0
tmp=$(mktemp)
tr -d '\r' < "$f" | sed '/^Made-with: Cursor[[:space:]]*$/d' > "$tmp" && mv "$tmp" "$f"
exit 0
