import type { DiscoverySourceCompany } from "../discovery.types.js";
import type { CompanySource } from "./source.interface.js";
import { normalizeSourceCompany } from "./source.interface.js";
import { ADDITIONAL_FORTUNE_ENTERPRISES } from "./fortune500.more.js";

export const FORTUNE_500_COMPANIES: DiscoverySourceCompany[] = [
  { name: "Walmart", domain: "walmart.com" },
  { name: "Amazon", domain: "amazon.jobs" },
  { name: "Apple", domain: "apple.com" },
  { name: "CVS Health", domain: "cvshealth.com" },
  { name: "UnitedHealth Group", domain: "unitedhealthgroup.com" },
  { name: "Berkshire Hathaway", domain: "berkshirehathaway.com" },
  { name: "Alphabet", domain: "abc.xyz" },
  { name: "Exxon Mobil", domain: "corporate.exxonmobil.com" },
  { name: "McKesson", domain: "mckesson.com" },
  { name: "Cencora", domain: "cencora.com" },
  { name: "Costco Wholesale", domain: "costco.com" },
  { name: "JPMorgan Chase", domain: "jpmorganchase.com" },
  { name: "Microsoft", domain: "microsoft.com" },
  { name: "Cardinal Health", domain: "cardinalhealth.com" },
  { name: "Chevron", domain: "chevron.com" },
  { name: "Cigna", domain: "cigna.com" },
  { name: "Ford Motor", domain: "ford.com" },
  { name: "Bank of America", domain: "bankofamerica.com" },
  { name: "General Motors", domain: "gm.com" },
  { name: "Elevance Health", domain: "elevancehealth.com" },
  { name: "Citigroup", domain: "citigroup.com" },
  { name: "Centene", domain: "centene.com" },
  { name: "Meta Platforms", domain: "meta.com" },
  { name: "Home Depot", domain: "homedepot.com" },
  { name: "Marathon Petroleum", domain: "marathonpetroleum.com" },
  { name: "Kroger", domain: "kroger.com" },
  { name: "Fannie Mae", domain: "fanniemae.com" },
  { name: "Walgreens Boots Alliance", domain: "walgreensbootsalliance.com" },
  { name: "Valero Energy", domain: "valero.com" },
  { name: "Verizon", domain: "verizon.com" },
  { name: "AT&T", domain: "att.com" },
  { name: "Comcast", domain: "corporate.comcast.com" },
  { name: "Wells Fargo", domain: "wellsfargo.com" },
  { name: "Tesla", domain: "tesla.com" },
  { name: "Phillips 66", domain: "phillips66.com" },
  { name: "Procter & Gamble", domain: "pg.com" },
  { name: "General Electric", domain: "ge.com" },
  { name: "IBM", domain: "ibm.com" },
  { name: "Intel", domain: "intel.com" },
  { name: "Cisco", domain: "cisco.com" },
  { name: "Oracle", domain: "oracle.com" },
  { name: "Salesforce", domain: "salesforce.com" },
  { name: "NVIDIA", domain: "nvidia.com" },
  { name: "Adobe", domain: "adobe.com" },
  { name: "PayPal", domain: "paypal.com" },
  { name: "Netflix", domain: "netflix.com" },
  { name: "Uber", domain: "uber.com" },
  { name: "Airbnb", domain: "airbnb.com" },
  { name: "DoorDash", domain: "doordash.com" },
  { name: "Coinbase", domain: "coinbase.com" },
  { name: "Goldman Sachs", domain: "goldmansachs.com" },
  { name: "Morgan Stanley", domain: "morganstanley.com" },
  { name: "BlackRock", domain: "blackrock.com" },
  { name: "AIG", domain: "aig.com" },
  { name: "Allstate", domain: "allstate.com" },
  { name: "State Farm", domain: "statefarm.com" },
  { name: "American Express", domain: "americanexpress.com" },
  { name: "Mastercard", domain: "mastercard.com" },
  { name: "Visa", domain: "visa.com" },
  { name: "Boeing", domain: "boeing.com" },
  { name: "Lockheed Martin", domain: "lockheedmartin.com" },
  { name: "Northrop Grumman", domain: "northropgrumman.com" },
  { name: "Raytheon", domain: "rtx.com" },
  { name: "3M", domain: "3m.com" },
  { name: "Honeywell", domain: "honeywell.com" },
  { name: "Caterpillar", domain: "caterpillar.com" },
  { name: "Deere & Company", domain: "deere.com" },
  { name: "PepsiCo", domain: "pepsico.com" },
  { name: "Coca-Cola", domain: "coca-colacompany.com" },
  { name: "Mondelez", domain: "mondelezinternational.com" },
  { name: "Kraft Heinz", domain: "kraftheinzcompany.com" },
  { name: "Tyson Foods", domain: "tysonfoods.com" },
  { name: "General Mills", domain: "generalmills.com" },
  { name: "Kellogg", domain: "kellanova.com" },
  { name: "Mars", domain: "mars.com" },
  { name: "Nike", domain: "nike.com" },
  { name: "Adidas", domain: "adidas.com" },
  { name: "Puma", domain: "puma.com" },
  { name: "Lululemon", domain: "lululemon.com" },
  { name: "Target", domain: "target.com" },
  { name: "Lowe's", domain: "lowes.com" },
  { name: "Best Buy", domain: "bestbuy.com" },
  { name: "eBay", domain: "ebay.com" },
  { name: "Etsy", domain: "etsy.com" },
  { name: "Wayfair", domain: "wayfair.com" },
  { name: "FedEx", domain: "fedex.com" },
  { name: "UPS", domain: "ups.com" },
  { name: "DHL", domain: "dhl.com" },
  { name: "Delta Air Lines", domain: "delta.com" },
  { name: "United Airlines", domain: "united.com" },
  { name: "American Airlines", domain: "aa.com" },
  { name: "Southwest Airlines", domain: "southwest.com" },
  { name: "JetBlue", domain: "jetblue.com" },
  { name: "Marriott International", domain: "marriott.com" },
  { name: "Hilton", domain: "hilton.com" },
  { name: "Hyatt", domain: "hyatt.com" },
  { name: "Accenture", domain: "accenture.com" },
  { name: "Deloitte", domain: "deloitte.com" },
  { name: "PwC", domain: "pwc.com" },
  { name: "KPMG", domain: "kpmg.com" },
  { name: "EY", domain: "ey.com" },
  { name: "Capgemini", domain: "capgemini.com" },
  { name: "Infosys", domain: "infosys.com" },
  { name: "TCS", domain: "tcs.com" },
  { name: "Wipro", domain: "wipro.com" },
  { name: "HCLTech", domain: "hcltech.com" },
  { name: "ServiceNow", domain: "servicenow.com" },
  { name: "Workday", domain: "workday.com" },
  { name: "SAP", domain: "sap.com" },
  { name: "Intuit", domain: "intuit.com" },
  { name: "HubSpot", domain: "hubspot.com" },
  { name: "Atlassian", domain: "atlassian.com" },
  { name: "Datadog", domain: "datadoghq.com" },
  { name: "Cloudflare", domain: "cloudflare.com" },
  { name: "Snowflake", domain: "snowflake.com" },
  { name: "Palantir", domain: "palantir.com" },
  { name: "Splunk", domain: "splunk.com" },
  { name: "MongoDB", domain: "mongodb.com" },
  { name: "Elastic", domain: "elastic.co" },
  { name: "Confluent", domain: "confluent.io" },
  { name: "Twilio", domain: "twilio.com" },
  { name: "Shopify", domain: "shopify.com" },
  { name: "Block", domain: "block.xyz" },
  { name: "Stripe", domain: "stripe.com" },
  { name: "Adyen", domain: "adyen.com" },
  { name: "Plaid", domain: "plaid.com" },
  { name: "Revolut", domain: "revolut.com" },
  { name: "Robinhood", domain: "robinhood.com" },
  { name: "Chime", domain: "chime.com" },
  { name: "SoFi", domain: "sofi.com" },
  { name: "Affirm", domain: "affirm.com" },
  { name: "Klarna", domain: "klarna.com" },
  { name: "N26", domain: "n26.com" },
  { name: "Wise", domain: "wise.com" },
  { name: "Zoom", domain: "zoom.us" },
  { name: "Slack", domain: "slack.com" },
  { name: "Dropbox", domain: "dropbox.com" },
  { name: "Box", domain: "box.com" },
  { name: "Asana", domain: "asana.com" },
  { name: "Notion", domain: "notion.so" },
  { name: "Canva", domain: "canva.com" },
  { name: "Figma", domain: "figma.com" },
  { name: "Miro", domain: "miro.com" },
  { name: "Monday.com", domain: "monday.com" },
  { name: "Smartsheet", domain: "smartsheet.com" },
  { name: "Okta", domain: "okta.com" },
  { name: "CrowdStrike", domain: "crowdstrike.com" },
  { name: "Palo Alto Networks", domain: "paloaltonetworks.com" },
  { name: "Fortinet", domain: "fortinet.com" },
  { name: "Check Point", domain: "checkpoint.com" },
  { name: "Zscaler", domain: "zscaler.com" },
  { name: "Akamai", domain: "akamai.com" },
  { name: "Fastly", domain: "fastly.com" },
  { name: "DigitalOcean", domain: "digitalocean.com" },
  { name: "Linode", domain: "linode.com" },
  { name: "OVHcloud", domain: "ovhcloud.com" },
  { name: "Rackspace", domain: "rackspace.com" },
  { name: "Nutanix", domain: "nutanix.com" },
  { name: "VMware", domain: "vmware.com" },
  { name: "Red Hat", domain: "redhat.com" },
  { name: "Canonical", domain: "canonical.com" },
  { name: "SUSE", domain: "suse.com" },
  { name: "HashiCorp", domain: "hashicorp.com" },
  { name: "GitHub", domain: "github.com" },
  { name: "GitLab", domain: "gitlab.com" },
  { name: "Bitbucket", domain: "bitbucket.org" },
  { name: "Databricks", domain: "databricks.com" },
  { name: "OpenAI", domain: "openai.com" },
  { name: "Anthropic", domain: "anthropic.com" },
  { name: "Cohere", domain: "cohere.com" },
  { name: "Scale AI", domain: "scale.com" },
  { name: "DeepMind", domain: "deepmind.google" },
  { name: "Perplexity", domain: "perplexity.ai" },
  { name: "Mistral AI", domain: "mistral.ai" },
  { name: "Hugging Face", domain: "huggingface.co" },
  { name: "Stability AI", domain: "stability.ai" },
  { name: "Runway", domain: "runwayml.com" },
  { name: "Midjourney", domain: "midjourney.com" },
  { name: "Anduril", domain: "anduril.com" },
  { name: "SpaceX", domain: "spacex.com" },
  { name: "Blue Origin", domain: "blueorigin.com" },
  { name: "Rocket Lab", domain: "rocketlabusa.com" },
  { name: "Northvolt", domain: "northvolt.com" },
  { name: "Rivian", domain: "rivian.com" },
  { name: "Lucid Motors", domain: "lucidmotors.com" },
  { name: "BYD", domain: "byd.com" },
  { name: "Siemens", domain: "siemens.com" },
  { name: "Schneider Electric", domain: "se.com" },
  { name: "ABB", domain: "abb.com" },
  { name: "Bosch", domain: "bosch.com" },
  { name: "Panasonic", domain: "panasonic.com" },
  { name: "Sony", domain: "sony.com" },
  { name: "Samsung", domain: "samsung.com" },
  { name: "LG", domain: "lg.com" },
  { name: "Toshiba", domain: "toshiba.com" },
  { name: "Hitachi", domain: "hitachi.com" },
  { name: "Baidu", domain: "baidu.com" },
  { name: "Tencent", domain: "tencent.com" },
  { name: "Alibaba", domain: "alibabagroup.com" },
  { name: "ByteDance", domain: "bytedance.com" },
  { name: "JD.com", domain: "jd.com" },
  { name: "Meituan", domain: "meituan.com" },
  { name: "PDD Holdings", domain: "pddholdings.com" },
  { name: "SAP SE", domain: "sap.com" },
  { name: "ASML", domain: "asml.com" },
  { name: "Arm", domain: "arm.com" },
  { name: "Qualcomm", domain: "qualcomm.com" },
  { name: "Broadcom", domain: "broadcom.com" },
  { name: "Micron", domain: "micron.com" },
  { name: "AMD", domain: "amd.com" },
  { name: "Texas Instruments", domain: "ti.com" },
  { name: "Applied Materials", domain: "appliedmaterials.com" },
  { name: "Lam Research", domain: "lamresearch.com" },
  { name: "KLA", domain: "kla.com" },
  { name: "Synopsys", domain: "synopsys.com" },
  { name: "Cadence", domain: "cadence.com" },
  ...ADDITIONAL_FORTUNE_ENTERPRISES,
];

async function fetchFortune500SourceCompanies(): Promise<DiscoverySourceCompany[]> {
  return FORTUNE_500_COMPANIES.map(normalizeSourceCompany).filter(
    (company) => company.name.length > 0,
  );
}

export const fortune500Source: CompanySource = {
  source: "fortune500",
  fetchCompanies: fetchFortune500SourceCompanies,
};

