import type { DiscoverySourceCompany } from "../discovery.types.js";

export const ADDITIONAL_FORTUNE_ENTERPRISES: DiscoverySourceCompany[] = [
  { name: "AbbVie", domain: "abbvie.com" },
  { name: "Abbott", domain: "abbott.com" },
  { name: "Aflac", domain: "aflac.com" },
  { name: "Albertsons", domain: "albertsons.com" },
  { name: "Alcoa", domain: "alcoa.com" },
  { name: "Alliant Energy", domain: "alliantenergy.com" },
  { name: "Altria", domain: "altria.com" },
  { name: "Ameren", domain: "ameren.com" },
  { name: "American Airlines Group", domain: "aa.com" },
  { name: "Ameriprise Financial", domain: "ameriprise.com" },
  { name: "Amgen", domain: "amgen.com" },
  { name: "Anheuser-Busch InBev", domain: "ab-inbev.com" },
  { name: "Archer Daniels Midland", domain: "adm.com" },
  { name: "AutoNation", domain: "autonation.com" },
  { name: "AutoZone", domain: "autozone.com" },
  { name: "Ball Corporation", domain: "ball.com" },
  { name: "Baxter International", domain: "baxter.com" },
  { name: "Biogen", domain: "biogen.com" },
  { name: "Bristol Myers Squibb", domain: "bms.com" },
  { name: "Brown-Forman", domain: "brown-forman.com" },
  { name: "Campbell Soup", domain: "campbellsoupcompany.com" },
  { name: "Capital One", domain: "capitalone.com" },
  { name: "CarMax", domain: "carmax.com" },
  { name: "Carrier Global", domain: "carrier.com" },
  { name: "Charles Schwab", domain: "schwab.com" },
  { name: "Charter Communications", domain: "charter.com" },
  { name: "Chubb", domain: "chubb.com" },
  { name: "Cincinnati Financial", domain: "cinfin.com" },
  { name: "Coca-Cola Europacific", domain: "coca-colaep.com" },
  { name: "Colgate-Palmolive", domain: "colgatepalmolive.com" },
  { name: "Conagra Brands", domain: "conagrabrands.com" },
  { name: "ConocoPhillips", domain: "conocophillips.com" },
  { name: "Consolidated Edison", domain: "conedison.com" },
  { name: "CooperCompanies", domain: "coopercos.com" },
  { name: "Copart", domain: "copart.com" },
  { name: "Corning", domain: "corning.com" },
  { name: "Corteva", domain: "corteva.com" },
  { name: "Crown Castle", domain: "crowncastle.com" },
  { name: "Cummins", domain: "cummins.com" },
  { name: "D.R. Horton", domain: "drhorton.com" },
  { name: "Danaher", domain: "danaher.com" },
  { name: "Darden Restaurants", domain: "darden.com" },
  { name: "Discover Financial", domain: "discover.com" },
  { name: "Dollar General", domain: "dollargeneral.com" },
  { name: "Dollar Tree", domain: "dollartree.com" },
  { name: "Dominion Energy", domain: "dominionenergy.com" },
  { name: "Dover", domain: "dovercorporation.com" },
  { name: "Dow", domain: "dow.com" },
  { name: "DTE Energy", domain: "dteenergy.com" },
  { name: "Duke Energy", domain: "duke-energy.com" },
  { name: "DuPont", domain: "dupont.com" },
  { name: "Eastman Chemical", domain: "eastman.com" },
  { name: "Ecolab", domain: "ecolab.com" },
  { name: "Edison International", domain: "edison.com" },
  { name: "Edwards Lifesciences", domain: "edwards.com" },
  { name: "Electronic Arts", domain: "ea.com" },
  { name: "Emerson Electric", domain: "emerson.com" },
  { name: "Entergy", domain: "entergy.com" },
  { name: "EOG Resources", domain: "eogresources.com" },
  { name: "Equifax", domain: "equifax.com" },
  { name: "Equinix", domain: "equinix.com" },
  { name: "Equity Residential", domain: "equityapartments.com" },
  { name: "Erie Insurance", domain: "erieinsurance.com" },
  { name: "Everest Group", domain: "everestre.com" },
  { name: "Evergy", domain: "evergy.com" },
  { name: "Eversource Energy", domain: "eversource.com" },
  { name: "Exelon", domain: "exeloncorp.com" },
  { name: "Expedia Group", domain: "expediagroup.com" },
  { name: "Expeditors International", domain: "expeditors.com" },
  { name: "Extra Space Storage", domain: "extraspace.com" },
  { name: "F5", domain: "f5.com" },
  { name: "FactSet", domain: "factset.com" },
  { name: "Farmers Insurance Exchange", domain: "farmers.com" },
  { name: "Fidelity National Financial", domain: "fnf.com" },
  { name: "Fifth Third Bancorp", domain: "53.com" },
  { name: "FirstEnergy", domain: "firstenergycorp.com" },
  { name: "Fiserv", domain: "fiserv.com" },
  { name: "FMC Corporation", domain: "fmc.com" },
  { name: "Foot Locker", domain: "footlocker.com" },
  { name: "Franklin Resources", domain: "franklinresources.com" },
  { name: "Freeport-McMoRan", domain: "fcx.com" },
  { name: "Gap", domain: "gapinc.com" },
  { name: "Garmin", domain: "garmin.com" },
  { name: "Gartner", domain: "gartner.com" },
  { name: "Gen Digital", domain: "gendigital.com" },
  { name: "Generac", domain: "generac.com" },
  { name: "Genuine Parts", domain: "genpt.com" },
  { name: "Gilead Sciences", domain: "gilead.com" },
  { name: "Global Payments", domain: "globalpayments.com" },
  { name: "Gold Fields", domain: "goldfields.com" },
  { name: "Goodyear", domain: "goodyear.com" },
  { name: "Grainger", domain: "grainger.com" },
  { name: "Halliburton", domain: "halliburton.com" },
  { name: "Hartford Financial", domain: "thehartford.com" },
  { name: "Hasbro", domain: "hasbro.com" },
  { name: "HCA Healthcare", domain: "hcahealthcare.com" },
  { name: "Henry Schein", domain: "henryschein.com" },
  { name: "Hershey", domain: "thehersheycompany.com" },
  { name: "Hess Corporation", domain: "hess.com" },
  { name: "Hologic", domain: "hologic.com" },
  { name: "HP", domain: "hp.com" },
  { name: "Humana", domain: "humana.com" },
  { name: "Huntington Bancshares", domain: "huntington.com" },
  { name: "Huntington Ingalls Industries", domain: "hii.com" },
  { name: "IDEXX Laboratories", domain: "idexx.com" },
  { name: "Illinois Tool Works", domain: "itw.com" },
  { name: "Incyte", domain: "incyte.com" },
  { name: "Ingredion", domain: "ingredion.com" },
  { name: "Intercontinental Exchange", domain: "ice.com" },
  { name: "International Paper", domain: "internationalpaper.com" },
  { name: "Interpublic Group", domain: "interpublic.com" },
  { name: "Intuitive Surgical", domain: "intuitive.com" },
  { name: "IQVIA", domain: "iqvia.com" },
  { name: "J.B. Hunt", domain: "jbhunt.com" },
  { name: "Jacobs Solutions", domain: "jacobs.com" },
  { name: "Johnson Controls", domain: "johnsoncontrols.com" },
  { name: "Jones Lang LaSalle", domain: "jll.com" },
  { name: "Kellanova", domain: "kellanova.com" },
  { name: "Keurig Dr Pepper", domain: "keurigdrpepper.com" },
  { name: "KeyCorp", domain: "key.com" },
  { name: "Kimberly-Clark", domain: "kimberly-clark.com" },
  { name: "Kimco Realty", domain: "kimcorealty.com" },
  { name: "Kinder Morgan", domain: "kindermorgan.com" },
  { name: "KKR", domain: "kkr.com" },
  { name: "L3Harris Technologies", domain: "l3harris.com" },
  { name: "Laboratory Corporation", domain: "labcorp.com" },
  { name: "Lear Corporation", domain: "lear.com" },
  { name: "Leidos", domain: "leidos.com" },
  { name: "Lennar", domain: "lennar.com" },
  { name: "Lilly", domain: "lilly.com" },
  { name: "Lincoln National", domain: "lincolnfinancial.com" },
  { name: "Live Nation Entertainment", domain: "livenationentertainment.com" },
  { name: "LKQ Corporation", domain: "lkqcorp.com" },
  { name: "Loews Corporation", domain: "loews.com" },
  { name: "Lumen Technologies", domain: "lumen.com" },
  { name: "LyondellBasell", domain: "lyondellbasell.com" },
  { name: "M&T Bank", domain: "mtb.com" },
  { name: "Marriott Vacations", domain: "marriottvacationsworldwide.com" },
  { name: "Marsh McLennan", domain: "marshmclennan.com" },
  { name: "Martin Marietta", domain: "martinmarietta.com" },
  { name: "Masco", domain: "masco.com" },
  { name: "McCormick", domain: "mccormickcorporation.com" },
  { name: "McDonald's", domain: "corporate.mcdonalds.com" },
  { name: "MetLife", domain: "metlife.com" },
  { name: "Mettler Toledo", domain: "mt.com" },
  { name: "MGM Resorts", domain: "mgmresorts.com" },
  { name: "Mohawk Industries", domain: "mohawkind.com" },
  { name: "Molina Healthcare", domain: "molinahealthcare.com" },
  { name: "Molson Coors", domain: "molsoncoors.com" },
  { name: "Monolithic Power Systems", domain: "monolithicpower.com" },
  { name: "Mosaic", domain: "mosaicco.com" },
  { name: "Motorola Solutions", domain: "motorolasolutions.com" },
  { name: "MSCI", domain: "msci.com" },
  { name: "Nasdaq", domain: "nasdaq.com" },
  { name: "National Grid", domain: "nationalgrid.com" },
  { name: "NCR Voyix", domain: "ncr.com" },
  { name: "NetApp", domain: "netapp.com" },
  { name: "Newmont", domain: "newmont.com" },
  { name: "News Corp", domain: "newscorp.com" },
  { name: "NextEra Energy", domain: "nexteraenergy.com" },
  { name: "NiSource", domain: "nisource.com" },
  { name: "Nordstrom", domain: "nordstrom.com" },
  { name: "Norfolk Southern", domain: "nscorp.com" },
  { name: "Northern Trust", domain: "northerntrust.com" },
  { name: "NRG Energy", domain: "nrg.com" },
  { name: "Nucor", domain: "nucor.com" },
  { name: "NVR", domain: "nvrinc.com" },
  { name: "O'Reilly Automotive", domain: "oreillyauto.com" },
  { name: "Occidental Petroleum", domain: "oxy.com" },
  { name: "Old Dominion Freight", domain: "odfl.com" },
  { name: "Omnicom Group", domain: "omnicomgroup.com" },
  { name: "ON Semiconductor", domain: "onsemi.com" },
  { name: "ONEOK", domain: "oneok.com" },
  { name: "Oracle NetSuite", domain: "netsuite.com" },
  { name: "Organon", domain: "organon.com" },
  { name: "Otis Worldwide", domain: "otis.com" },
  { name: "Owens Corning", domain: "owenscorning.com" },
  { name: "Paccar", domain: "paccar.com" },
  { name: "Packaging Corporation", domain: "packagingcorp.com" },
  { name: "Parker Hannifin", domain: "parker.com" },
  { name: "Pentair", domain: "pentair.com" },
  { name: "Pfizer", domain: "pfizer.com" },
  { name: "PG&E", domain: "pge.com" },
  { name: "Philip Morris International", domain: "pmi.com" },
  { name: "Pinnacle West", domain: "pinnaclewest.com" },
  { name: "PNC Financial", domain: "pnc.com" },
  { name: "Pool Corporation", domain: "poolcorp.com" },
  { name: "PPG Industries", domain: "ppg.com" },
  { name: "PPL Corporation", domain: "pplweb.com" },
  { name: "Principal Financial", domain: "principal.com" },
  { name: "Progressive", domain: "progressive.com" },
  { name: "Prudential Financial", domain: "prudential.com" },
  { name: "Public Service Enterprise", domain: "pseg.com" },
  { name: "Public Storage", domain: "publicstorage.com" },
  { name: "PulteGroup", domain: "pultegroup.com" },
  { name: "Qorvo", domain: "qorvo.com" },
  { name: "Quest Diagnostics", domain: "questdiagnostics.com" },
  { name: "Regeneron", domain: "regeneron.com" },
  { name: "Regions Financial", domain: "regions.com" },
  { name: "Republic Services", domain: "republicservices.com" },
  { name: "ResMed", domain: "resmed.com" },
  { name: "Rockwell Automation", domain: "rockwellautomation.com" },
  { name: "Rollins", domain: "rollins.com" },
  { name: "Roper Technologies", domain: "ropertech.com" },
  { name: "Ross Stores", domain: "rossstores.com" },
  { name: "Royal Caribbean", domain: "royalcaribbean.com" },
  { name: "S&P Global", domain: "spglobal.com" },
  { name: "Schlumberger", domain: "slb.com" },
  { name: "Seagate Technology", domain: "seagate.com" },
  { name: "Sempra", domain: "sempra.com" },
  { name: "Sherwin-Williams", domain: "sherwin-williams.com" },
  { name: "Simon Property Group", domain: "simon.com" },
  { name: "Skyworks Solutions", domain: "skyworksinc.com" },
  { name: "Smith & Nephew", domain: "smith-nephew.com" },
  { name: "Smithfield Foods", domain: "smithfieldfoods.com" },
  { name: "Snap-on", domain: "snapon.com" },
  { name: "Solventum", domain: "solventum.com" },
  { name: "Southern Company", domain: "southerncompany.com" },
  { name: "Southwest Gas", domain: "southwestgas.com" },
  { name: "Stanley Black & Decker", domain: "stanleyblackanddecker.com" },
  { name: "State Street", domain: "statestreet.com" },
  { name: "Steris", domain: "steris.com" },
  { name: "Stryker", domain: "stryker.com" },
  { name: "Synchrony Financial", domain: "synchrony.com" },
  { name: "Sysco", domain: "sysco.com" },
  { name: "T. Rowe Price", domain: "troweprice.com" },
  { name: "Take-Two Interactive", domain: "take2games.com" },
  { name: "Tapestry", domain: "tapestry.com" },
  { name: "TE Connectivity", domain: "te.com" },
  { name: "Teledyne Technologies", domain: "teledyne.com" },
  { name: "Teradyne", domain: "teradyne.com" },
  { name: "Textron", domain: "textron.com" },
  { name: "Thermo Fisher Scientific", domain: "thermofisher.com" },
  { name: "Tractor Supply", domain: "tractorsupply.com" },
  { name: "Trane Technologies", domain: "tranetechnologies.com" },
  { name: "TransDigm Group", domain: "transdigm.com" },
  { name: "Travelers", domain: "travelers.com" },
  { name: "Trimble", domain: "trimble.com" },
  { name: "Truist Financial", domain: "truist.com" },
  { name: "Tyler Technologies", domain: "tylertech.com" },
  { name: "UDR", domain: "udr.com" },
  { name: "Ulta Beauty", domain: "ulta.com" },
  { name: "Under Armour", domain: "underarmour.com" },
  { name: "Union Pacific", domain: "up.com" },
  { name: "United Rentals", domain: "unitedrentals.com" },
  { name: "United Therapeutics", domain: "unither.com" },
  { name: "Universal Health Services", domain: "uhs.com" },
  { name: "Unum Group", domain: "unum.com" },
  { name: "US Bancorp", domain: "usbank.com" },
  { name: "Ventas", domain: "ventasreit.com" },
  { name: "Verisign", domain: "verisign.com" },
  { name: "Vertex Pharmaceuticals", domain: "vrtx.com" },
  { name: "VF Corporation", domain: "vfc.com" },
  { name: "Viatris", domain: "viatris.com" },
  { name: "Vici Properties", domain: "viciproperties.com" },
  { name: "Vistra", domain: "vistracorp.com" },
  { name: "Vulcan Materials", domain: "vulcanmaterials.com" },
  { name: "W.R. Berkley", domain: "wrberkley.com" },
  { name: "Waste Management", domain: "wm.com" },
  { name: "Waters Corporation", domain: "waters.com" },
  { name: "Welltower", domain: "welltower.com" },
  { name: "West Pharmaceutical", domain: "westpharma.com" },
  { name: "Western Digital", domain: "westerndigital.com" },
  { name: "WestRock", domain: "westrock.com" },
  { name: "Weyerhaeuser", domain: "weyerhaeuser.com" },
  { name: "Whirlpool", domain: "whirlpoolcorp.com" },
  { name: "Williams Companies", domain: "williams.com" },
  { name: "Willis Towers Watson", domain: "wtwco.com" },
  { name: "Wynn Resorts", domain: "wynnresorts.com" },
  { name: "Xcel Energy", domain: "xcelenergy.com" },
  { name: "Xylem", domain: "xylem.com" },
  { name: "Yum Brands", domain: "yum.com" },
  { name: "Zebra Technologies", domain: "zebra.com" },
  { name: "Zimmer Biomet", domain: "zimmerbiomet.com" },
  { name: "Zoetis", domain: "zoetis.com" },
];
