import type { Metadata } from "next";
import { LegalPageShell } from "../../../components/legal/LegalPageShell";
import { getGoverningLawJurisdiction, getSupportEmail, LEGAL_LAST_UPDATED } from "../../../lib/siteIdentity";

export const metadata: Metadata = {
  title: "Terms of Service | JobLoom",
  description: "Terms of Service for the JobLoom product and website.",
};

export default function TermsPage() {
  const support = getSupportEmail();
  const law = getGoverningLawJurisdiction();

  return (
    <LegalPageShell
      title="Terms of Service"
      description={`Last updated: ${LEGAL_LAST_UPDATED}.`}
    >
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of the websites, applications, and services
        offered by JobLoom (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) (collectively, the &quot;Service&quot;). By
        creating an account, subscribing, or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        JobLoom is a job aggregation and search tool. Depending on your plan, you may access job listings, search and filter
        features, an account, optional resume upload and related processing, and optional features such as a browser extension
        (&quot;Smart Apply&quot;). The mix of free and paid features is described on our site and may change. We do not guarantee
        that any listing is complete, current, or accurate, that any role will still be open when you apply, or that you will
        obtain employment, an interview, or any particular outcome. The Service is not a recruiting or placement service.
      </p>

      <h2>2. Eligibility and accounts</h2>
      <p>
        You must provide accurate registration information. Authentication and account management may be provided by a
        third-party sign-in service. You are responsible for safeguarding your credentials and for activity under your account.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service in violation of applicable law or third-party rights.</li>
        <li>Attempt to probe, scan, or test the vulnerability of our systems, or bypass rate limits or access controls.</li>
        <li>Use the Service to transmit malware, spam, or deceptive content.</li>
        <li>Reverse engineer or attempt to extract source code or models except where permitted by law.</li>
        <li>Misrepresent your identity, qualifications, or affiliation when applying to roles.</li>
      </ul>

      <h2>4. Subscriptions and billing</h2>
      <p>
        Certain features require a paid subscription. Payments for subscriptions are processed by a <strong>third-party payment
        provider</strong> that may act as the <strong>Merchant of Record</strong>. This means the payment provider may handle
        billing, invoicing, tax collection, and certain aspects of refunds and first-line payment support, as described at
        checkout, in your receipt, and in the provider&apos;s terms. We receive the information we need to activate, renew, and
        manage your access to paid features. Fees, billing period (for example, monthly or annual), and taxes are shown at
        purchase.
      </p>
      <p>
        <strong>Subscriptions renew automatically</strong> at the end of each billing period <strong>unless you cancel</strong>{" "}
        prior to renewal, as described in our <a href="/billing">Billing, cancellation, and refunds</a> page and at checkout. By
        subscribing, you authorize recurring charges through the third-party payment provider in line with the plan you select.
        If a payment fails, we may suspend paid features until payment succeeds or the subscription ends.
      </p>

      <h2>5. Cancellation</h2>
      <p>
        You may cancel a subscription through the account or subscription controls we provide, including any billing or
        customer portal made available by the third-party payment provider. When you cancel, you generally retain access to
        paid features <strong>until the end of the period you have already paid for</strong>, unless otherwise stated at
        purchase. See our <a href="/billing">Billing, cancellation, and refunds</a> page.
      </p>

      <h2>6. AI-assisted and extension features</h2>
      <p>
        Some features may generate suggestions or draft text using automated or AI-assisted methods. Output may be inaccurate or
        incomplete. <strong>You are solely responsible</strong> for reviewing, editing, and submitting applications and for the
        accuracy of information you provide to employers. Nothing generated by the Service constitutes legal, career, tax, or
        professional advice, or any promise of employment or compensation.
      </p>
      <p>
        The Smart Apply extension may interact with third-party career sites to help fill forms from your profile. You must
        review every submission. The extension may request broad site access to function; see our{" "}
        <a href="/privacy">Privacy Policy</a> for more detail.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        The Service, including software, branding, and content we create, is owned by us or our licensors. Job listings and
        third-party content remain the property of their respective owners. Subject to these Terms, we grant you a limited,
        non-exclusive, non-transferable license to use the Service for personal job search purposes.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE
        DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE OR OUR SUPPLIERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
        SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS OPPORTUNITY, ARISING
        OUT OF OR RELATED TO THE SERVICE OR THESE TERMS. OUR AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL
        NOT EXCEED THE GREATER OF (A) THE <strong>FEES PAID FOR THE SERVICE</strong> IN THE TWELVE MONTHS BEFORE THE CLAIM OR
        (B) FIFTY U.S. DOLLARS (OR THE EQUIVALENT IN LOCAL CURRENCY), EXCEPT WHERE PROHIBITED BY LAW. &quot;FEES PAID FOR THE
        SERVICE&quot; INCLUDES AMOUNTS PROCESSED BY A THIRD-PARTY PAYMENT PROVIDER IN CONNECTION WITH YOUR SUBSCRIPTION, TO THE
        EXTENT THOSE AMOUNTS RELATE TO YOUR ACCESS TO THE SERVICE.
      </p>

      <h2>10. Indemnity</h2>
      <p>
        You will defend and indemnify us against any claims, damages, losses, and expenses (including reasonable attorneys&apos;
        fees) arising from your use of the Service, your content, your applications to employers, or your violation of these
        Terms.
      </p>

      <h2>11. Changes</h2>
      <p>
        We may modify the Service or these Terms. If we make material changes, we will provide notice as appropriate (for
        example, by posting an updated date or contacting you at the email on your account). Continued use after changes become
        effective constitutes acceptance of the revised Terms.
      </p>

      <h2>12. Termination; data</h2>
      <p>
        We may suspend or terminate access to the Service if you materially breach these Terms, if we are required to do so by
        law, or to protect the Service or other users. You may stop using the Service at any time. You may also request
        deletion of your personal information or your account; see our <a href="/privacy">Privacy Policy</a> for how to make a
        request, subject to legal exceptions. Provisions of these Terms that by their nature should survive will survive
        termination.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These Terms are governed by the laws of {law}, excluding conflict-of-law rules that would apply another
        jurisdiction&apos;s laws, except where mandatory consumer protections apply.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms:{" "}
        {support ? (
          <a href={`mailto:${support}`} className="font-medium text-brand hover:underline">
            {support}
          </a>
        ) : (
          <>the contact method published on this website.</>
        )}
      </p>
    </LegalPageShell>
  );
}
