import type { Metadata } from "next";
import { LegalPageShell } from "../../../components/legal/LegalPageShell";
import {
  getGoverningLawJurisdiction,
  getSiteOperator,
  getSupportEmail,
} from "../../../lib/siteIdentity";

export const metadata: Metadata = {
  title: "Terms of Service | JobSeek",
  description: "Terms of Service for the JobSeek product and website.",
};

export default function TermsPage() {
  const operator = getSiteOperator();
  const support = getSupportEmail();
  const law = getGoverningLawJurisdiction();

  return (
    <LegalPageShell
      title="Terms of Service"
      description={`Last updated: ${new Date().toLocaleDateString("en-GB", { year: "numeric", month: "long", day: "numeric" })}. Template — have qualified counsel review before reliance.`}
    >
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of the websites, applications, and services
        offered by {operator} (&quot;we,&quot; &quot;us,&quot; or &quot;JobSeek&quot;) (collectively, the &quot;Service&quot;). By creating an account,
        subscribing, or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        JobSeek provides job search tools, including aggregated job listings, filters, account features, optional resume-related
        features, and optional browser extension functionality (&quot;Smart Apply&quot;). Features may change over time. We do not
        guarantee that any particular job listing will remain available, that listings are error-free, or that you will obtain
        employment or interviews by using the Service.
      </p>

      <h2>2. Eligibility and accounts</h2>
      <p>
        You must provide accurate registration information. Authentication and account management may be provided by a third
        party (such as Clerk). You are responsible for safeguarding your credentials and for activity under your account.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service in violation of applicable law or third-party rights.</li>
        <li>Attempt to probe, scan, or test the vulnerability of our systems, or bypass rate limits or access controls.</li>
        <li>Use the Service to transmit malware, spam, or deceptive content.</li>
        <li>Reverse engineer or attempt to extract source code or models except where permitted by law.</li>
        <li>Misrepresent your identity, qualifications, or affiliation when applying to roles.</li>
      </ul>

      <h2>4. Subscriptions and billing</h2>
      <p>
        Paid plans are billed by {operator} through a third-party payment processor. Fees, renewal terms, and taxes (if any) are
        presented at checkout. By subscribing, you authorize charges in accordance with the plan you select. If your payment
        fails, we may suspend paid features until payment succeeds.
      </p>

      <h2>5. Cancellation</h2>
      <p>
        You may cancel a subscription in accordance with the billing portal or account controls we provide. When you cancel,
        you typically retain access through the end of the period you already paid for, unless stated otherwise at purchase.
        See also our <a href="/billing">Billing &amp; refunds</a> page.
      </p>

      <h2>6. AI-assisted and extension features</h2>
      <p>
        Some features may generate suggestions or draft text using automated or AI-assisted methods. Output may be inaccurate or
        incomplete. <strong>You are solely responsible</strong> for reviewing, editing, and submitting applications and for the
        accuracy of information you provide to employers. Nothing generated by the Service constitutes legal, career, or
        professional advice.
      </p>
      <p>
        The Smart Apply extension may interact with third-party career sites to help fill forms based on your profile. You must
        review every submission. The extension may request broad site access to function; see our <a href="/privacy">Privacy Policy</a>{" "}
        for more detail.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        The Service, including software, branding, and content we create, is owned by us or our licensors. Job listings and
        third-party content remain the property of their respective owners. Subject to these Terms, we grant you a limited,
        non-exclusive, non-transferable license to use the Service for personal job search purposes.
      </p>

      <h2>8. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL
        WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL {operator.toUpperCase()} OR ITS SUPPLIERS BE LIABLE FOR ANY
        INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS
        OPPORTUNITY, ARISING OUT OF OR RELATED TO THE SERVICE OR THESE TERMS. OUR AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO
        THE SERVICE WILL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE MONTHS BEFORE THE
        CLAIM OR (B) FIFTY U.S. DOLLARS (OR THE EQUIVALENT IN LOCAL CURRENCY), EXCEPT WHERE PROHIBITED BY LAW.
      </p>

      <h2>10. Indemnity</h2>
      <p>
        You will defend and indemnify us against any claims, damages, losses, and expenses (including reasonable attorneys&apos;
        fees) arising from your use of the Service, your content, your applications to employers, or your violation of these
        Terms.
      </p>

      <h2>11. Changes</h2>
      <p>
        We may modify the Service or these Terms. If we make material changes, we will provide notice as appropriate (for
        example, by posting an updated date or email where we have your address). Continued use after changes become effective
        constitutes acceptance of the revised Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate access to the Service if you materially breach these Terms or if we must do so to comply with
        law or protect the Service or other users.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These Terms are governed by the laws of {law}, excluding conflict-of-law rules that would apply another jurisdiction&apos;s
        laws, except where mandatory consumer protections apply.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms:{" "}
        {support ? (
          <a href={`mailto:${support}`} className="font-medium text-brand hover:underline">
            {support}
          </a>
        ) : (
          <>use the contact method published on this website when available.</>
        )}
      </p>
    </LegalPageShell>
  );
}
