-- AlterTable
ALTER TABLE "User" ADD COLUMN     "address" TEXT,
ADD COLUMN     "applyProfileSummary" JSONB,
ADD COLUMN     "availableFrom" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "country" TEXT,
ADD COLUMN     "currentCompany" TEXT,
ADD COLUMN     "currentTitle" TEXT,
ADD COLUMN     "customQA" JSONB,
ADD COLUMN     "firstName" TEXT,
ADD COLUMN     "githubUrl" TEXT,
ADD COLUMN     "lastName" TEXT,
ADD COLUMN     "linkedinUrl" TEXT,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "portfolioUrl" TEXT,
ADD COLUMN     "professionalSummary" TEXT,
ADD COLUMN     "salaryExpectation" TEXT,
ADD COLUMN     "smartApplyEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smartApplyJobsToday" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "smartApplyResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "workAuthorization" TEXT,
ADD COLUMN     "yearsOfExperience" INTEGER;
