-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resumeContentHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profileExtractLastAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "currentCompensation" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "noticePeriod" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "relocationPreference" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "remotePreference" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "languages" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "certifications" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "highestEducation" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "smartApplyPreferences" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "applyProfileExtras" JSONB;
